### ISSUE TITLE
um590使用问题，菜单卡顿，没有其他问题

### ISSUE THREAD

**Issue by hobbyzhu** [daliansky/minisforum-UM590-UM580D-Hackintosh#1]
你好um590使用问题，菜单卡顿，几秒就恢复，原因为止，这个EFI可以直接使用吗？我安装的是14.4勾选14.4的intel网卡，其他网卡取消。还需要进行其他修改吗？我看关于本机的处理器信息并不对，不知道是否有影响

**Comment by hobbyzhu** [comment]
666跟新了

**Comment by YujiaCheng1996** [comment]
UM580D 菜单还是卡顿，关闭模糊会好一点

**Comment by hobbyzhu** [comment]
> UM580D 菜单还是卡顿，关闭模糊会好一点
要自己替换NootedRed最近这个作者解决了这些问题

**Comment by YujiaCheng1996** [comment]
> > UM580D 菜单还是卡顿，关闭模糊会好一点
> > 要自己替换NootedRed最近这个作者解决了这些问题

确实，只要替换NootedRed到最新版就好了
